# Generated by Django 4.2.4 on 2023-09-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_empresa_usuariovinculado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='correo',
            new_name='ciudad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
