# Generated by Django 4.2.4 on 2023-09-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='empresaVinculado',
            new_name='empresaVinculada',
        ),
    ]
