# Generated by Django 4.2.4 on 2023-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_rename_correo_empresa_ciudad_remove_empresa_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
