# Generated by Django 4.2.4 on 2023-09-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_rename_estadoproyecto_proyecto_estadoproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ciudad',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='departamento',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='direccion',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
