# Generated by Django 4.2.4 on 2023-09-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_empresa_direccion'),
        ('administracion', '0007_proyecto_ciudad_proyecto_departamento_and_more'),
    ]

    operations = [
    ]
