# Generated by Django 4.2.4 on 2023-09-11 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_alter_perfil_celular'),
        ('administracion', '0008_merge_20230910_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='coordinadorVinculado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.perfil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuarioVinculado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.perfil'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='empresaVinculada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa'),
        ),
    ]
