# Generated by Django 4.2.4 on 2023-09-12 23:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0007_proyecto_ciudad_proyecto_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('referencia', models.CharField(max_length=150)),
                ('unidad', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.CharField(default='Si', max_length=5)),
                ('nombreMarca', models.CharField(max_length=200)),
                ('tipoInsumo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaCaducidad', models.DateTimeField(default='')),
                ('fechaCompra', models.DateTimeField(default=datetime.datetime.now)),
                ('observaciones', models.CharField(default='', max_length=300)),
                ('proyectoAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.proyecto')),
            ],
        ),
    ]
