# Generated by Django 4.2.4 on 2023-09-13 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_insumo_fechacaducidad_alter_insumo_fechacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='fechaCaducidad',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fechaCompra',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 20, 58, 21, 380956)),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fechaIngreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 20, 58, 21, 380956)),
        ),
    ]
