# Generated by Django 4.2.4 on 2023-09-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_insumo_fechacaducidad_alter_insumo_fechacompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='fechaCompra',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fechaIngreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
