# Generated by Django 4.2.4 on 2023-10-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_alter_perfil_celular'),
        ('administracion', '0009_proyecto_coordinadorvinculado_and_more'),
        ('inventario', '0005_alter_insumo_fechacompra_alter_insumo_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='valorUnitario',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='TransferenciaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('estado', models.CharField(default='Pendiente', max_length=15)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='autenticacion.perfil')),
                ('coordinadorSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinadorSolicitante', to='autenticacion.perfil')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('proyectoDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoDestino', to='administracion.proyecto')),
                ('proyectoOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoOrigen', to='administracion.proyecto')),
            ],
        ),
    ]
