# Generated by Django 4.2.6 on 2023-10-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_insumo_fechacompra_alter_insumo_fechaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='valorUnitario',
            field=models.FloatField(),
        ),
    ]
