# Generated by Django 4.2.6 on 2023-10-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_insumo_cantidad_alter_insumo_valorunitario_and_more'),
        ('inventario', '0006_insumo_categoria_alter_insumo_cantidad_and_more'),
    ]

    operations = [
    ]
