# Generated by Django 4.2.6 on 2023-11-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_proyecto_coordinadorvinculado_and_more'),
        ('inventario', '0007_merge_20231023_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('tipo', models.CharField(max_length=15)),
                ('observaciones', models.CharField(default='', max_length=300)),
                ('proyectoAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.proyecto')),
            ],
        ),
    ]
