# Generated by Django 4.2.7 on 2023-11-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_costosproyecto'),
        ('inventario', '0008_insumo_correofechaingreso_insumo_correovencimiento_and_more'),
        ('inventario', '0008_insumo_paravender_costosproyecto'),
        ('inventario', '0008_transferenciainsumo_costotransferencia_and_more'),
    ]

    operations = [
    ]
