# Generated by Django 4.2.4 on 2023-09-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='celular',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombreCargo',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
