# Generated by Django 4.2.4 on 2023-09-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_perfil_celular_alter_perfil_nombrecargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='celular',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
